feat: add oscd-select based on wizard-select
openscd/oscd-form-elements pull request #6
Opened 2023-08-03 18:04 UTC by Stef3st

closes #3

2023-08-29 13:22 UTC, juancho0202 approved these changes
I think this meets our [component guide](https://github.com/openscd/.github/blob/23491bd2408f3b7edaa8b0149a3d57aca1adaf40/docs/component_guide.md). You can merge with or without my CEM comments suggestions.

2023-08-30 07:53 UTC, pascalwilbrink requested changes

2023-08-30 07:53 UTC, pascalwilbrink commented on components/oscd-select/src/oscd-select.ts
> + * @tag oscd-select
none of the props are documented

2023-08-30 07:53 UTC, pascalwilbrink commented on components/oscd-select/src/oscd-select.ts
> +  reservedValues: string[] = [];
not used

2023-08-30 12:20 UTC, Stef3st commented on components/oscd-select/src/oscd-select.ts
> + * @tag oscd-select
They are documented, but above the properties themselves. The CEM analyzer will get these aswell.

2023-08-30 12:21 UTC, Stef3st commented on components/oscd-select/src/oscd-select.ts
> +  reservedValues: string[] = [];
This is copied from the wizard-select. Will this never be used? Then Im ok with removing the property

2023-09-07 14:44 UTC, juancho0202 approved these changes
Annotations look good and the removed property is the same as the one that @pascalwilbrink pointed out

2023-09-07 14:45 UTC, merged